server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: catalogRoute
          uri: lb://catalog-service/
          predicates:
            - Path=/catalog/**
        - id: movieRoute
          uri: lb://movie-service/
          predicates:
            - Path=/movies/**
        - id: serieRoute
          uri: lb://serie-service/
          predicates:
<<<<<<< HEAD
            - Path=/api/v1/series/**
=======
            - Path=//api/v1/series/**
>>>>>>> 7e7d08c4ac4cd8f1fba464e9e1f28f5f6f4be231


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
